export default database = {
  tasks: [
    {
      TaskId: 0,
      TaskName: 'Trash',
      CloneFrom: 0,
      ContentAssigned: 'Adkjfla;sdf',
      ContentHandlingWork: 'asdfdfasdfas',
      Description: 'Nice',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 0,
      StatusName: 'New',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'Nice',
      Processor: 0,
      ProcesssorName: 'Nice',
      Acceptance: true,
      AcceptanceName: 'AAA',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'aaa',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 1,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description:
        'asdfffffffffffffffffffffffffffffffffffffffffffffffffffff;j;lasdjf;ajsdfasd',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 1,
      StatusName: 'Old',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 2,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description:
        'asdfffffffffffffffffffffffffffffffffffffffffffffffffffff;j;lasdjf;ajsdfasd',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 1,
      StatusName: 'Old',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 3,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description:
        'asdfffffffffffffffffffffffffffffffffffffffffffffffffffff;j;lasdjf;ajsdfasd',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 1,
      StatusName: 'Old',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 4,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description:
        'asdfffffffffffffffffffffffffffffffffffffffffffffffffffff;j;lasdjf;ajsdfasd',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 1,
      StatusName: 'Old',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 5,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description:
        'asdfffffffffffffffffffffffffffffffffffffffffffffffffffff;j;lasdjf;ajsdfasd',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 1,
      StatusName: 'Old',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
  ],
  users: [
    {
      Id: 0,
      Username: 'admin',
      Password: 'admin',
      RoleID: 1,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
    {
      Id: 4,
      Username: 'Somebody',
      Password: 'admin',
      RoleID: 3,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
    {
      Id: 2,
      Username: 'manager',
      Password: 'admin',
      RoleID: 2,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
    {
      Id: 1,
      Username: 'new',
      Password: 'admin',
      RoleID: 2,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
  ],
  groups: [
    {
      GroupId: 1,
      GroupName: 'Hoang',
      MangerId: 1,
    },
    {
      GroupId: 2,
      GroupName: 'Hoang',
      MangerId: 2,
    },
    {
      GroupId: 3,
      GroupName: 'Hoang',
      MangerId: null,
    },
  ],
};
